name: Build

on:
  push:
    branches:
      - master

jobs:
  build:
    if: "startsWith(github.event.head_commit.message, '[build]')"
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout sources
        uses: actions/checkout@v5
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: "liberica"
          java-version: 17
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          build-scan-publish: true
          build-scan-terms-of-use-url: "https://gradle.com/terms-of-service"
          build-scan-terms-of-use-agree: "yes"
      - name: Build with Gradle
        run: |
          java -version
          chmod +x ./gradlew
          ./gradlew -v
          ./gradlew clean
          ./gradlew build
          ./gradlew version
          echo "build_version=$(cat version)" >> $GITHUB_ENV
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.2
        with:
          custom_tag: ${{ env.build_version }}
          tag_prefix: ""
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Create a GitHub release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ env.build_version }}
          name: "${{ github.event.repository.name }} ${{ env.build_version }}"
          generateReleaseNotes: true